export const USER_SET_ID = 'USER_SET_ID';
export const USER_SET_PICTURE = 'USER_SET_PICTURE';

export const POSTINGS_SET_POSTINGS = 'POSTINGS_SET_POSTINGS';
export const POSTINGS_SET_POSTING_BY_ID = 'POSTINGS_SET_POSTING_BY_ID';
